import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Nyasha',
      email: 'nyasha@outlook.com',
      password: bcrypt.hashSync('0123456'),
      isAdmin: true,
    },
    {
      name: 'Daniels',
      email: 'daniels@outlook.com',
      password: bcrypt.hashSync('0123456'),
      isAdmin: true,
    },
    {
      name: 'Musanhu',
      email: 'musanhu@outlook.com',
      password: bcrypt.hashSync('0123456'),
      isAdmin: false,
    },
    {
      name: 'testuser',
      email: 'test@user.com',
      password: bcrypt.hashSync('0123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'HP Beast',
      slug: 'computer-hp',
      category: 'HP computers',
      image: '/images/hp.jpg ',
      price: 12560,
      brand: 'HP',
      rating: 4.2,
      numReviews: 458,
      countInStock: 10,
      description: 'A great machine',
    },
    {
      name: 'Dell Valentine',
      slug: 'computer-dell',
      category: 'HP computers',
      image: '/images/dell.jpg',
      price: 12000,
      brand: 'DELL',
      rating: 4.35,
      numReviews: 209,
      countInStock: 19,
      description: 'Great Hardware',
    },
    {
      name: 'Macbook Sand',
      slug: 'computer-apple',
      category: 'Mac machine',
      image: '/images/mac.jpg ',
      price: 13930,
      brand: 'Mac',
      rating: 4.5,
      numReviews: 892,
      countInStock: 12,
      description: 'Flawless Computer',
    },
    {
      name: 'Acer Legend',
      slug: 'computer-acer',
      category: 'Acer Computer',
      image: '/images/asus.jpg',
      price: 8900,
      brand: 'Acer',
      rating: 3.9,
      numReviews: 567,
      countInStock: 17,
      description: 'Cheap Yet Trendy',
    },
    {
      name: 'Lenovo Delta',
      slug: 'computer-lenovo',
      category: 'Lenovo computer',
      image: '/images/lenovo.jpg ',
      price: 9200,
      brand: 'Lenovo',
      rating: 4.12,
      numReviews: 601,
      countInStock: 8,
      description: 'Effective and Reliable',
    },
    {
      name: 'Samsung Pro',
      slug: 'computer-samsung',
      category: 'Samsung computer',
      image: '/images/samsung1.jpg ',
      price: 13002,
      brand: 'Samsung',
      rating: 4.73,
      numReviews: 394,
      countInStock: 5,
      description: 'One of the best out there',
    },
  ],
};

export default data;
